(function(g){var window=this;'use strict';var $z=function(l){l.publish("autonavvisibility")},rFR=function(l,y){g.G3(l,"onAutonavCoundownStarted",y)},Q2=function(l){return l.isBackground()&&l.Bw()},ZpR=function(l,y){y=y.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
l.Y=y?.navigationEndpoint;y=y?.trackingParams;l.playButton&&y&&l.L.setTrackingParams(l.playButton.element,y)},dB=function(l){const y=tk(l);
var k=Math,z=k.min;var r=l.K?Date.now()-l.K:0;k=z.call(k,r,y);Ot(l,Math.ceil((y-k)/1E3));y-k<=500&&l.Z()?l.select(!0):l.Z()&&l.D.start()},wB=function(l){var y=l.L.rz(!0,l.L.isFullscreen());
g.I(l.container.element,"ytp-autonav-endscreen-small-mode",l.xw(y));g.I(l.container.element,"ytp-autonav-endscreen-is-premium",!!l.suggestion&&!!l.suggestion.V7);g.I(l.L.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!l.L.pg());g.I(l.L.getRootNode(),"countdown-running",l.Z());g.I(l.container.element,"ytp-player-content",l.L.pg());g.n9(l.overlay.element,{width:`${y.width}px`});if(!l.Z()){l.L.pg()?Ot(l,Math.round(tk(l)/1E3)):Ot(l);y=!!l.suggestion&&!!l.suggestion.Cx;const k=l.L.pg()||!y;g.I(l.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!k&&y);g.I(l.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",k&&!y);l.S.fP(l.L.pg())}},Ot=function(l,y=-1){l=l.V.qd("ytp-autonav-endscreen-upnext-header");
g.Uq(l);if(y>=0){y=String(y);const k="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],z="Up next in $SECONDS".indexOf(k);if(z>=0){l.appendChild(g.ap("Up next in $SECONDS".slice(0,z)));const r=g.Gf("span");g.yp(r,"ytp-autonav-endscreen-upnext-header-countdown-number");g.C9(r,y);l.appendChild(r);l.appendChild(g.ap("Up next in $SECONDS".slice(z+k.length)));return}}g.C9(l,"Up next")},tk=function(l){return l.L.isFullscreen()?(l=l.L.getVideoData()?.kC,l===-1||l===void 0?8E3:l):l.L.SD()>=0?l.L.SD():
g.i_(l.L.O().experiments,"autoplay_time")||1E4},hk=function(l,y){y=eG2(l,y);
var k=Math,z=k.min;var r=(0,g.f)()-l.K;k=z.call(k,r,y);y=y===0?1:Math.min(k/y,1);l.HG.setAttribute("stroke-dashoffset",`${-211*(y+1)}`);y>=1&&l.Z()&&l.api.getPresentingPlayerType()!==3?l.select(!0):l.Z()&&l.V.start()},eG2=function(l,y){return y?y:l.api.isFullscreen()?(l=l.api.getVideoData()?.kC,l===-1||l===void 0?8E3:l):l.api.SD()>=0?l.api.SD():g.i_(l.api.O().experiments,"autoplay_time")||1E4},G2=function(l){const y=l.pg();
y!==l.K&&(l.K=y,$z(l.player),l.K?(l.C!==l.Z&&l.C.hide(),l.table.hide()):(l.C!==l.Z&&l.C.show(),l.table.show()))},ar=function(l){return g.Ki(l.player)&&l.V()&&!l.J},iy=function(l){const y=l.pg();
y!==l.D&&(l.D=y,$z(l.player))},Ut=function(l){return g.Ki(l.player)&&l.V()&&!l.S},ME=function(l){const y=l.pg();
y!==l.b0&&(l.b0=y,$z(l.player))},AFO=function(l){l=l.O();
return l.BF&&!l.I4&&!l.disableOrganicUi},$oR=function(l){const y=l.player.getVideoData();
if(!y||l.Z===y.zA&&l.C===y.hv)return!1;l.Z=y.zA;l.C=y.hv;return!0},Qkx=function(l){l.player.Ur("endscreen");
var y=l.player.getVideoData();y=new g.N1(Math.max((y.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const k=new g.N1(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});l.player.Wa([y,k])};
g.hc.prototype.SD=g.k4(9,function(){return this.app.SD()});
g.zY.prototype.SD=g.k4(8,function(){return this.getVideoData().sQ});
g.wa.prototype.JA=g.k4(7,function(l){this.KS().JA(l)});
g.TF.prototype.JA=g.k4(6,function(l){this.J9!==l&&(this.J9=l,this.YN())});
var tqR=class extends g.H{constructor(l){const y=l.O(),k=y.V;super({U:"a",B:"ytp-autonav-suggestion-card",G:{href:"{{url}}",target:k?y.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{U:"div",L_:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],G:{style:"{{background}}"},W:[{U:"div",G:{"aria-label":"{{timestamp}}"},L_:["ytp-autonav-timestamp"],Nd:"{{duration}}"},
{U:"div",L_:["ytp-autonav-live-stamp"],Nd:"Live"},{U:"div",L_:["ytp-autonav-upcoming-stamp"],Nd:"Upcoming"},{U:"div",B:"ytp-autonav-list-overlay",W:[{U:"div",B:"ytp-autonav-mix-text",Nd:"Mix"},{U:"div",B:"ytp-autonav-mix-icon"}]}]},{U:"div",L_:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Nd:"{{title}}"},{U:"div",L_:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Nd:"{{author}}"},{U:"div",L_:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
Nd:"{{views_and_publish_time}}"}]});this.L=l;this.suggestion=null;this.Z=k;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.L.E2(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.PL||void 0)&&this.L.logClick(this.element)}onClick(l){g.Bl(l,this.L,this.Z,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(l){switch(l.keyCode){case 13:case 32:l.defaultPrevented||(this.select(),l.preventDefault())}}};var X6=class extends g.H{constructor(l,y=!1){super({U:"div",B:"ytp-autonav-endscreen-countdown-overlay"});this.HG=y;this.cancelCommand=this.Y=void 0;this.K=0;this.container=new g.H({U:"div",B:"ytp-autonav-endscreen-countdown-container"});g.x(this,this.container);this.container.Uj(this.element);y=l.O();const k=y.V;this.L=l;this.suggestion=null;this.onVideoDataChange("newdata",this.L.getVideoData());this.j(l,"videodatachange",this.onVideoDataChange);this.V=new g.H({U:"div",B:"ytp-autonav-endscreen-upnext-container",
G:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{U:"div",B:"ytp-autonav-endscreen-upnext-header"},{U:"div",B:"ytp-autonav-endscreen-upnext-alternative-header",Nd:"{{autoplayAlternativeHeader}}"},{U:"a",B:"ytp-autonav-endscreen-link-container",G:{href:"{{url}}",target:k?y.D:""},W:[{U:"div",B:"ytp-autonav-endscreen-upnext-thumbnail",G:{style:"{{background}}"},W:[{U:"div",G:{"aria-label":"{{timestamp}}"},
L_:["ytp-autonav-timestamp"],Nd:"{{duration}}"},{U:"div",L_:["ytp-autonav-live-stamp"],Nd:"Live"},{U:"div",L_:["ytp-autonav-upcoming-stamp"],Nd:"Upcoming"}]},{U:"div",B:"ytp-autonav-endscreen-video-info",W:[{U:"div",B:"ytp-autonav-endscreen-premium-badge"},{U:"div",B:"ytp-autonav-endscreen-upnext-title",Nd:"{{title}}"},{U:"div",B:"ytp-autonav-endscreen-upnext-author",Nd:"{{author}}"},{U:"div",B:"ytp-autonav-view-and-date",Nd:"{{views_and_publish_time}}"},{U:"div",B:"ytp-autonav-author-and-view",Nd:"{{author_and_views}}"}]}]}]});
g.x(this,this.V);this.V.Uj(this.container.element);k||this.j(this.V.qd("ytp-autonav-endscreen-link-container"),"click",this.sj);this.L.createClientVe(this.container.element,this,115127);this.L.createClientVe(this.V.qd("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.H({U:"div",B:"ytp-autonav-overlay"});g.x(this,this.overlay);this.overlay.Uj(this.container.element);this.S=new g.H({U:"div",B:"ytp-autonav-endscreen-button-container"});g.x(this,this.S);this.S.Uj(this.container.element);
this.cancelButton=new g.H({U:"button",L_:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],G:{"aria-label":"Cancel autoplay"},Nd:"Cancel"});g.x(this,this.cancelButton);this.cancelButton.Uj(this.S.element);this.cancelButton.listen("click",this.Ja,this);this.L.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.H({U:"a",L_:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],G:{href:"{{url}}",role:"button","aria-label":"Play next video"},Nd:"Play Now"});g.x(this,this.playButton);this.playButton.Uj(this.S.element);this.playButton.listen("click",this.sj,this);this.L.createServerVe(this.playButton.element,this.playButton,!0);(y=this.L.getVideoData())&&ZpR(this,y);this.D=new g.B_(()=>{dB(this)},500);
g.x(this,this.D);this.b0();this.j(l,"autonavvisibility",this.b0)}A(l){this.suggestion!==l&&(this.suggestion=l,g.xK(this.V,l),this.playButton.updateValue("url",this.suggestion.A6()),wB(this))}Z(){return this.K>0}J(){this.Z()||(this.K=Date.now(),dB(this),rFR(this.L,tk(this)),g.I(this.L.getRootNode(),"countdown-running",this.Z()))}N(){this.C();dB(this);const l=this.V.qd("ytp-autonav-endscreen-upnext-header");l&&g.C9(l,"Up next")}C(){this.Z()&&(this.D.stop(),this.K=0)}select(l=!1){this.L.nextVideo(!1,
l);this.C()}sj(l){g.Bl(l,this.L)&&(l.currentTarget===this.playButton.element?this.L.logClick(this.playButton.element):l.currentTarget===this.V.qd("ytp-autonav-endscreen-link-container")&&(l=this.V.qd("ytp-autonav-endscreen-link-container"),this.L.logVisibility(l,!0),this.L.logClick(l)),this.Y?(g.G3(this.L,"innertubeCommand",this.Y),this.C()):this.select())}Ja(){this.L.logClick(this.cancelButton.element);g.Io(this.L,!0);this.cancelCommand&&g.G3(this.L,"innertubeCommand",this.cancelCommand)}onVideoDataChange(l,
y){ZpR(this,y);this.cancelCommand=y.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}b0(){const l=this.L.pg();this.HG&&this.VM!==l&&this.fP(l);wB(this);this.L.logVisibility(this.container.element,l);this.L.logVisibility(this.cancelButton.element,l);this.L.logVisibility(this.V.qd("ytp-autonav-endscreen-link-container"),l);this.L.logVisibility(this.playButton.element,l)}xw(l){return l.width<400||l.height<459}};var cT=class extends g.H{constructor(l,y){super({U:"div",L_:["html5-endscreen","ytp-player-content",y||"base-endscreen"]});this.created=!1;this.player=l}create(){this.created=!0}destroy(){this.created=!1}V(){return!1}pg(){return!1}Y(){return!1}};var Cs=class extends g.H{constructor(l){super({U:"div",L_:["ytp-upnext","ytp-player-content"],G:{"aria-label":"{{aria_label}}"},W:[{U:"div",B:"ytp-cued-thumbnail-overlay-image",G:{style:"{{background}}"}},{U:"span",B:"ytp-upnext-top",W:[{U:"span",B:"ytp-upnext-header",Nd:"Up Next"},{U:"span",B:"ytp-upnext-title",Nd:"{{title}}"},{U:"span",B:"ytp-upnext-author",Nd:"{{author}}"}]},{U:"a",B:"ytp-upnext-autoplay-icon",G:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{U:"svg",G:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},W:[{U:"circle",B:"ytp-svg-autoplay-circle",G:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{U:"circle",B:"ytp-svg-autoplay-ring",G:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{U:"path",B:"ytp-svg-fill",G:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{U:"span",B:"ytp-upnext-bottom",W:[{U:"span",B:"ytp-upnext-cancel"},
{U:"span",B:"ytp-upnext-paused",Nd:"Autoplay is paused"}]}]});this.api=l;this.cancelButton=null;this.HG=this.qd("ytp-svg-autoplay-ring");this.D=this.notification=this.V=this.suggestion=null;this.Y=new g.B_(this.S,5E3,this);this.K=0;var y=this.qd("ytp-upnext-cancel");this.cancelButton=new g.H({U:"button",L_:["ytp-upnext-cancel-button","ytp-button"],G:{tabindex:"0","aria-label":"Cancel autoplay"},Nd:"Cancel"});g.x(this,this.cancelButton);this.cancelButton.listen("click",this.sj,this);this.cancelButton.Uj(y);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.x(this,this.Y);this.api.createClientVe(this.element,this,18788);y=this.qd("ytp-upnext-autoplay-icon");this.j(y,"click",this.Ja);this.api.createClientVe(y,this,115130);this.b0();this.j(l,"autonavvisibility",this.b0);this.j(l,"mdxnowautoplaying",this.RR);this.j(l,"mdxautoplaycanceled",this.rb);g.I(this.element,"ytp-upnext-mobile",this.api.O().C)}S(){this.notification&&(this.Y.stop(),this.uq(this.D),this.D=null,this.notification.close(),
this.notification=null)}A(l){this.suggestion=l;g.xK(this,l,"hqdefault.jpg")}b0(){this.fP(this.api.pg());this.api.logVisibility(this.element,this.api.pg());this.api.logVisibility(this.qd("ytp-upnext-autoplay-icon"),this.api.pg());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.pg())}u0(){window.focus();this.S()}J(l){this.Z()||(g.yD("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.K=(0,g.f)(),this.V=new g.B_(()=>{hk(this,l)},25),hk(this,l),rFR(this.api,eG2(this,
l)));
g.ZM(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}Z(){return!!this.V}N(){this.C();this.K=(0,g.f)();hk(this);g.zi(this.element,"ytp-upnext-autoplay-paused")}C(){this.Z()&&(this.V.dispose(),this.V=null)}select(l=!1){if(this.api.O().X("autonav_notifications")&&l&&window.Notification&&typeof document.hasFocus==="function"){const y=Notification.permission;y==="default"?Notification.requestPermission():y!=="granted"||document.hasFocus()||(this.S(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.uE()}),this.D=this.j(this.notification,"click",this.u0),this.Y.start())}this.C();this.api.nextVideo(!1,l)}Ja(l){!g.cf(this.cancelButton.element,l.target)&&g.Bl(l,this.api)&&(this.api.pg()&&this.api.logClick(this.qd("ytp-upnext-autoplay-icon")),this.select())}sj(){this.api.pg()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Io(this.api,!0)}RR(l){this.api.getPresentingPlayerType();this.show();this.J(l)}rb(){this.api.getPresentingPlayerType();
this.C();this.hide()}Vj(){this.C();this.S();super.Vj()}};var dox=class extends cT{constructor(l){super(l,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.H({U:"div",B:"ytp-suggestion-panel",W:[{U:"div",L_:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Nd:"More videos"}]});this.D=new g.H({U:"div",B:"ytp-suggestions-container"});this.videos=[];this.N=null;this.K=this.A=!1;this.C=new X6(this.player);g.x(this,this.C);this.C.Uj(this.element);l.getVideoData().hv?this.Z=this.C:(this.Z=new Cs(l),g.pi(this.player,
this.Z.element,4),g.x(this,this.Z));this.overlay=new g.H({U:"div",B:"ytp-autonav-overlay-cancelled-state"});g.x(this,this.overlay);this.overlay.Uj(this.element);this.J=new g.cI(this);g.x(this,this.J);g.x(this,this.table);this.table.Uj(this.element);this.table.show();g.x(this,this.D);this.D.Uj(this.table.element);this.hide()}create(){super.create();this.J.j(this.player,"appresize",this.S);this.J.j(this.player,"onVideoAreaChange",this.S);this.J.j(this.player,"videodatachange",this.onVideoDataChange);
this.J.j(this.player,"autonavchange",this.b0);this.J.j(this.player,"onAutonavCancelled",this.sj);this.onVideoDataChange()}show(){super.show();(this.A||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.Io(this.player,!1);g.Ki(this.player)&&this.V()&&!this.N?(G2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||Q2(this.player.gT())&&this.player.X("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.N()):(g.Io(this.player,
!0),G2(this));this.S()}hide(){super.hide();this.Z.N();G2(this)}S(){var l=this.player.rz(!0,this.player.isFullscreen());G2(this);wB(this.C);g.I(this.element,"ytp-autonav-cancelled-small-mode",this.xw(l));g.I(this.element,"ytp-autonav-cancelled-tiny-mode",this.tK(l));g.I(this.element,"ytp-autonav-cancelled-mini-mode",l.width<=400||l.height<=360);this.overlay&&g.n9(this.overlay.element,{width:`${l.width}px`});if(!this.K)for(l=0;l<this.videos.length;l++)g.I(this.videos[l].element,"ytp-suggestion-card-with-margin",
l%2===1)}onVideoDataChange(){var l=this.player.getVideoData();if(this.videoData!==l&&l){this.videoData=l;l=this.videoData.suggestions;var y=this.videoData.D();y&&(this.Z.A(y),this.Z!==this.C&&this.C.A(y));if(l&&l.length)for(let z=0;z<OpR.length;++z){var k=OpR[z];l&&l[k]&&(this.videos[z]=new tqR(this.player),y=this.videos[z],k=l[k],y.suggestion!==k&&(y.suggestion=k,g.xK(y,k)),g.x(this,this.videos[z]),this.videos[z].Uj(this.D.element))}this.S()}}b0(l){l===1?(this.A=!1,this.N=this.videoData.clientPlaybackNonce,
this.Z.C(),this.VM&&this.S()):(this.A=!0,this.pg()&&(l===2?this.Z.J():l===3&&this.Z.N()))}sj(l){l?this.b0(1):(this.N=null,this.A=!1)}V(){return this.videoData.autonavState!==1}xw(l){return(l.width<910||l.height<459)&&!this.tK(l)&&!(l.width<=400||l.height<=360)}tK(l){return l.width<800&&!(l.width<=400||l.height<=360)}pg(){return this.VM&&g.Ki(this.player)&&this.V()&&!this.N}},OpR=[1,3,2,4];var w$x=class extends cT{constructor(l){super(l,"videowall-endscreen");this.L=l;this.stills=[];this.J=this.videoData=null;this.S=this.D=!1;this.b0=null;g.zi(this.element,"modern-videowall-endscreen");this.C=new g.cI(this);g.x(this,this.C);this.K=new g.B_(()=>{g.zi(this.element,"ytp-show-tiles")},0);
g.x(this,this.K);this.table=new g.Ev({U:"div",B:"ytp-modern-endscreen-content"});g.x(this,this.table);this.table.Uj(this.element);l.getVideoData().hv?this.Z=new X6(l,!0):this.Z=new Cs(l);g.x(this,this.Z);g.pi(this.player,this.Z.element,4);l.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var l=this.player.getVideoData();l&&(this.videoData=l);this.N();this.C.j(this.player,"appresize",this.N);this.C.j(this.player,"onVideoAreaChange",this.N);this.C.j(this.player,"videodatachange",
this.onVideoDataChange);this.C.j(this.player,"autonavchange",this.A);this.C.j(this.player,"onAutonavCancelled",this.sj);l=this.videoData.autonavState;l!==this.b0&&this.A(l);this.C.j(this.element,"transitionend",this.Ja)}destroy(){this.C.C();g.kj(this.stills);this.stills=[];super.destroy();g.ZM(this.element,"ytp-show-tiles");this.K.stop();this.b0=this.videoData.autonavState}V(){return this.videoData.autonavState!==1}show(){const l=this.VM;super.show();g.ZM(this.element,"ytp-show-tiles");this.player.O().C?
g.H_(this.K):this.K.start();(this.S||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.Io(this.player,!1);ar(this)?(iy(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||Q2(this.player.gT())&&this.player.X("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.N()):(g.Io(this.player,!0),iy(this));l!==this.VM&&this.player.logVisibility(this.element,!0)}hide(){const l=this.VM;super.hide();this.Z.N();iy(this);l!==this.VM&&this.player.logVisibility(this.element,
!1)}Ja(l){l.target===this.element&&this.N()}N(){const l=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.D()];if(l.length){var y=this.L.rz(!0,this.L.isFullscreen()),k=Math.floor((y.width-64+16)/(g.gf(y.width*.27,250,450)+16));y=Math.min(3,Math.floor((y.height-64)/((y.width-64-(k-1)*16)/k*.5625+70)));g.eM(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.zi(this.element,`ytp-modern-endscreen-limit-rows-${y}`);
g.I(this.element,"ytp-modern-endscreen-single-item",k===1);g.I(this.element,"ytp-modern-endscreen-row-0",y===0);k=this.table.element;k.ariaLive="polite";this.Z.A(this.videoData.D());this.Z instanceof X6&&wB(this.Z);g.I(this.element,"ytp-endscreen-takeover",ar(this));iy(this);y=0;k.ariaBusy="true";var z=l.length;for(let r=0;r<z;r++){const Z=r%z;let e=this.stills[r];e||(e=new g.Wvo(this.player),this.stills[r]=e,k.appendChild(e.element));g.Gas(e,l[Z]);y++}this.stills.length=y}}onVideoDataChange(){const l=
this.player.getVideoData({playerType:1});this.videoData!==l&&(l?.D()?(this.videoData=l,this.N()):this.player.Md("missg",{vid:l?.videoId||"",cpn:l?.clientPlaybackNonce||""}))}Y(){return this.Z.Z()}A(l){l===1?(this.S=!1,this.J=this.videoData.clientPlaybackNonce,this.Z.C(),this.VM&&this.N()):(this.S=!0,this.VM&&ar(this)&&(l===2?this.Z.J():l===3&&this.Z.N()))}sj(l){if(l){for(l=0;l<this.stills.length;l++)this.L.logVisibility(this.stills[l].element,!0);this.A(1)}else this.J=null,this.S=!1;this.N()}pg(){return this.VM&&
ar(this)}};var hGy=class extends cT{constructor(l){super(l,"subscribecard-endscreen");this.Z=new g.H({U:"div",B:"ytp-subscribe-card",W:[{U:"img",B:"ytp-author-image",G:{src:"{{profilePicture}}"}},{U:"div",B:"ytp-subscribe-card-right",W:[{U:"div",B:"ytp-author-name",Nd:"{{author}}"},{U:"div",B:"html5-subscribe-button-container"}]}]});g.x(this,this.Z);this.Z.Uj(this.element);const y=l.getVideoData();this.subscribeButton=new g.UD("Subscribe",null,"Unsubscribe",null,!0,!1,y.Fu,y.subscribed,"trailer-endscreen",null,
l,!1);g.x(this,this.subscribeButton);this.subscribeButton.Uj(this.Z.qd("html5-subscribe-button-container"));this.j(l,"videodatachange",this.Aa);this.Aa();this.hide()}Aa(){const l=this.player.getVideoData();this.Z.update({profilePicture:l.profilePicture,author:l.author});this.subscribeButton.channelId=l.Fu;var y=this.subscribeButton;l.subscribed?y.Z():y.C()}};var GMR=class extends g.H{constructor(l){const y=l.O(),k=g.Mx||g.Yf?{style:"will-change: opacity"}:void 0,z=y.V,r=["ytp-videowall-still"];y.C&&r.push("ytp-videowall-show-text");super({U:"a",L_:r,G:{href:"{{url}}",target:z?y.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{U:"div",B:"ytp-videowall-still-image",G:{style:"{{background}}"}},{U:"span",B:"ytp-videowall-still-info",G:{"aria-hidden":"true"},W:[{U:"span",B:"ytp-videowall-still-info-bg",
W:[{U:"span",B:"ytp-videowall-still-info-content",G:k,W:[{U:"span",B:"ytp-videowall-still-info-title",Nd:"{{title}}"},{U:"span",B:"ytp-videowall-still-info-author",Nd:"{{author_and_views}}"},{U:"span",B:"ytp-videowall-still-info-live",Nd:"Live"},{U:"span",B:"ytp-videowall-still-info-duration",Nd:"{{duration}}"}]}]}]},{U:"span",L_:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],G:{"aria-hidden":"true"},W:[{U:"span",B:"ytp-videowall-still-listlabel-icon"},"Playlist",{U:"span",
B:"ytp-videowall-still-listlabel-length",W:[" (",{U:"span",Nd:"{{playlist_length}}"},")"]}]},{U:"span",L_:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],G:{"aria-hidden":"true"},W:[{U:"span",B:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{U:"span",B:"ytp-videowall-still-listlabel-length",Nd:" (50+)"}]}]});this.suggestion=null;this.C=z;this.api=l;this.Z=new g.cI(this);g.x(this,this.Z);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.Z.j(l,"videodatachange",
this.onVideoDataChange);l.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.E2(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.PL||void 0)&&this.api.logClick(this.element)}onClick(l){if(g.u9(this.api.O())&&this.api.X("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let y=this.suggestion.A6();const k={};g.JI(this.api,k);y=g.UI(y,k);g.Hl(y,this.api,l)}else g.Bl(l,this.api,
this.C,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(l){switch(l.keyCode){case 13:case 32:l.defaultPrevented||(this.select(),l.preventDefault())}}onVideoDataChange(){const l=this.api.getVideoData(),y=this.api.O();this.C=l.Wn?!1:y.V}};var aOB=class extends cT{constructor(l){super(l,"videowall-endscreen");this.L=l;this.J=0;this.stills=[];this.S=this.videoData=null;this.K=this.b0=!1;this.sj=null;this.N=new g.cI(this);g.x(this,this.N);this.A=new g.B_(()=>{g.zi(this.element,"ytp-show-tiles")},0);
g.x(this,this.A);var y=new g.H({U:"button",L_:["ytp-button","ytp-endscreen-previous"],G:{"aria-label":"Previous"},W:[g.OP()]});g.x(this,y);y.Uj(this.element);y.listen("click",this.RR,this);this.table=new g.Ev({U:"div",B:"ytp-endscreen-content"});g.x(this,this.table);this.table.Uj(this.element);y=new g.H({U:"button",L_:["ytp-button","ytp-endscreen-next"],G:{"aria-label":"Next"},W:[g.dM()]});g.x(this,y);y.Uj(this.element);y.listen("click",this.HG,this);l.getVideoData().hv?this.Z=new X6(l,!0):this.Z=
new Cs(l);g.x(this,this.Z);g.pi(this.player,this.Z.element,4);l.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var l=this.player.getVideoData();l&&(this.videoData=l);this.C();this.N.j(this.player,"appresize",this.C);this.N.j(this.player,"onVideoAreaChange",this.C);this.N.j(this.player,"videodatachange",this.onVideoDataChange);this.N.j(this.player,"autonavchange",this.D);this.N.j(this.player,"onAutonavCancelled",this.Ja);l=this.videoData.autonavState;l!==this.sj&&this.D(l);
this.N.j(this.element,"transitionend",this.rb)}destroy(){this.N.C();g.kj(this.stills);this.stills=[];super.destroy();g.ZM(this.element,"ytp-show-tiles");this.A.stop();this.sj=this.videoData.autonavState}V(){return this.videoData.autonavState!==1}show(){const l=this.VM;super.show();g.ZM(this.element,"ytp-show-tiles");this.player.O().C?g.H_(this.A):this.A.start();(this.K||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.Io(this.player,!1);Ut(this)?(ME(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||Q2(this.player.gT())&&this.player.X("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.N()):(g.Io(this.player,!0),ME(this));l!==this.VM&&this.player.logVisibility(this.element,!0)}hide(){const l=this.VM;super.hide();this.Z.N();ME(this);l!==this.VM&&this.player.logVisibility(this.element,!1)}rb(l){l.target===this.element&&this.C()}C(){var l=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.D()];if(l.length){g.zi(this.element,
"ytp-endscreen-paginate");var y=this.L.rz(!0,this.L.isFullscreen()),k=g.Ci(this.L);k&&(k=k.qV()?48:32,y.width-=k*2);var z=y.width/y.height,r=96/54,Z=k=2,e=Math.max(y.width/96,2),A=Math.max(y.height/54,2),Q=l.length;var t=Q*4;for(t-=4;t>0&&(k<e||Z<A);){var O=k/2,d=Z/2,w=k<=e-2&&t>=d*4,h=Z<=A-2&&t>=O*4;if((O+1)/d*r/z>z/(O/(d+1)*r)&&h)t-=O*4,Z+=2;else if(w)t-=d*4,k+=2;else if(h)t-=O*4,Z+=2;else break}r=!1;t>=12&&Q*4-t<=6&&(Z>=4||k>=4)&&(r=!0);t=k*96;e=Z*54;z=t/e<z?y.height/e:y.width/t;z=Math.min(z,2);
t=Math.floor(Math.min(y.width,t*z));e=Math.floor(Math.min(y.height,e*z));y=this.table.element;y.ariaLive="polite";g.r7(y,t,e);g.n9(y,{marginLeft:`${t/-2}px`,marginTop:`${e/-2}px`});this.Z.A(this.videoData.D());this.Z instanceof X6&&wB(this.Z);g.I(this.element,"ytp-endscreen-takeover",Ut(this));ME(this);t+=4;e+=4;z=0;y.ariaBusy="true";for(A=0;A<k;A++)for(O=0;O<Z;O++)if(w=z,h=0,r&&A>=k-2&&O>=Z-2?h=1:O%2===0&&A%2===0&&(O<2&&A<2?O===0&&A===0&&(h=2):h=2),w=g.Em(w+this.J,Q),h!==0){d=this.stills[z];d||(d=
new GMR(this.player),this.stills[z]=d,y.appendChild(d.element));var U=Math.floor(e*O/Z);const u=Math.floor(t*A/k),W=Math.floor(e*(O+h)/Z)-U-4,V=Math.floor(t*(A+h)/k)-u-4;g.Hf(d.element,u,U);g.r7(d.element,V,W);g.n9(d.element,"transitionDelay",(O+A)/20+"s");g.I(d.element,"ytp-videowall-still-mini",h===1);g.I(d.element,"ytp-videowall-still-large",h>2);h=Math.max(V,W);g.I(d.element,"ytp-videowall-still-round-large",h>=256);g.I(d.element,"ytp-videowall-still-round-medium",h>96&&h<256);g.I(d.element,"ytp-videowall-still-round-small",
h<=96);w=l[w];d.suggestion!==w&&(d.suggestion=w,h=d.api.O(),U=g.ka(d.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.xK(d,w,U),g.u9(h)&&!d.api.X("web_player_log_click_before_generating_ve_conversion_params")&&(h=w.A6(),U={},g.UB(d.api,"addEmbedsConversionTrackingParams",[U]),h=g.UI(h,U),d.updateValue("url",h)),(w=(w=w.sessionData)&&w.itct)&&d.api.setTrackingParams(d.element,w));z++}y.ariaBusy="false";g.I(this.element,"ytp-endscreen-paginate",z<Q);for(l=this.stills.length-1;l>=
z;l--)k=this.stills[l],g.XI(k.element),g.yb(k);this.stills.length=z}}onVideoDataChange(){const l=this.player.getVideoData({playerType:1});this.videoData!==l&&(l?.D()?(this.J=0,this.videoData=l,this.C()):this.player.Md("missg",{vid:l?.videoId||"",cpn:l?.clientPlaybackNonce||""}))}HG(){this.J+=this.stills.length;this.C()}RR(){this.J-=this.stills.length;this.C()}Y(){return this.Z.Z()}D(l){l===1?(this.K=!1,this.S=this.videoData.clientPlaybackNonce,this.Z.C(),this.VM&&this.C()):(this.K=!0,this.VM&&Ut(this)&&
(l===2?this.Z.J():l===3&&this.Z.N()))}Ja(l){if(l){for(l=0;l<this.stills.length;l++)this.L.logVisibility(this.stills[l].element,!0);this.D(1)}else this.S=null,this.K=!1;this.C()}pg(){return this.VM&&Ut(this)}};var ipo=class extends g.H{constructor(l){super({U:"button",L_:["ytp-watch-on-youtube-button","ytp-button"],Nd:"{{content}}"});this.L=l;this.buttonType=this.buttonType=1;this.Z();this.buttonType===2&&g.zi(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Z);this.fP(!0)}Z(){let l,y;switch(this.buttonType){case 1:l="Watch again on YouTube";y=156915;break;case 2:l="Continue watching on YouTube";y=156942;break;default:l="Continue watching on YouTube",
y=156942}this.update({content:l});this.L.hasVe(this.element)&&this.L.destroyVe(this.element);this.L.createClientVe(this.element,this,y)}onClick(l){this.L.X("web_player_log_click_before_generating_ve_conversion_params")&&this.L.logClick(this.element);g.Hl(this.getVideoUrl(),this.L,l);this.L.X("web_player_log_click_before_generating_ve_conversion_params")||this.L.logClick(this.element)}getVideoUrl(){var l=!0;switch(this.buttonType){case 1:l=!0;break;case 2:l=!1}l=this.L.getVideoUrl(l,!1,!1,!0);const y=
this.L.O();if(g.u9(y)){const k={};g.u9(y)&&g.UB(this.L,"addEmbedsConversionTrackingParams",[k]);l=g.UI(l,k)}return l}logVisibility(){this.L.logVisibility(this.element,this.VM&&this.C_)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Cl(l){super.Cl(l);this.logVisibility()}};var UoR=class extends cT{constructor(l){super(l,"watch-again-on-youtube-endscreen");this.watchButton=new ipo(l);g.x(this,this.watchButton);this.watchButton.Uj(this.element);g.Hge(l)&&(this.Z=new g.tUw(l),g.x(this,this.Z),this.C=new g.H({U:"div",L_:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],G:{tabIndex:"-1"},W:[this.Z]}),g.x(this,this.C),this.Z.Uj(this.C.element),this.C.Uj(this.element));l.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.Z?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const y=this.C;if(y){var l=this.Z.hasSuggestions();g.I(this.element,"ytp-shorts-branded-ui",l);l?y.show():y.hide()}g.Ci(this.player)?.JA(!0);this.player.logVisibility(this.element,!0);this.watchButton.Cl(!0)}}hide(){super.hide();g.Ci(this.player)?.JA(!1);this.player.logVisibility(this.element,!1);this.watchButton.Cl(!1)}};g.EZ("endscreen",class extends g.f1{constructor(l){super(l);this.endScreen=null;this.Z=this.C=this.N=!1;this.listeners=new g.cI(this);g.x(this,this.listeners);const y=l.O();l.isEmbedsShortsMode()?this.endScreen=new UoR(l):AFO(l)?(this.N=!0,$oR(this),this.Z?this.endScreen=new dox(l):y.X("delhi_modern_endscreen")?this.endScreen=new w$x(l):this.endScreen=new aOB(l)):y.I4?this.endScreen=new hGy(l):this.endScreen=new cT(l);g.x(this,this.endScreen);g.pi(l,this.endScreen.element,4);Qkx(this);this.listeners.j(l,
"videodatachange",this.onVideoDataChange,this);this.listeners.j(l,g.uR("endscreen"),k=>{this.onCueRangeEnter(k)});
this.listeners.j(l,g.xR("endscreen"),k=>{this.onCueRangeExit(k)})}wz(){var l=this.player.getVideoData();
const y=l.mutedAutoplay&&(l.limitedPlaybackDurationInSeconds>0||l.endSeconds>0||l.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!y)return!0;var k=!(!l?.D()&&!l?.suggestions?.length);k=!AFO(this.player)||k;l=l.SW;const z=this.player.pU();return k&&!l&&!z&&!y}pg(){return this.endScreen.pg()}Pq(){return this.pg()?this.endScreen.Y():!1}Vj(){this.player.Ur("endscreen");super.Vj()}load(){{const k=this.player.getVideoData(),z=k.transitionEndpointAtEndOfStream;if(z&&z.videoId){var l=
this.player.r4().R4.get("heartbeat");var y=k.D();!y||z.videoId!==y.videoId||k.rS?(this.player.E2(z.videoId,void 0,void 0,!0,!0,z),l&&l.qX("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),l=!0):l=!1}else l=!1}l||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(l){this.wz()&&(this.endScreen.created||this.endScreen.create(),l.getId()==="load"&&this.load())}onCueRangeExit(l){l.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){Qkx(this);this.N&&$oR(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.Z?this.endScreen=new dox(this.player):this.endScreen=new aOB(this.player),g.x(this,this.endScreen),g.pi(this.player,this.endScreen.element,4))}});})(_yt_player);
